spring.application.name=aurevia

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:AureviaProductionJWTSecret2026SecureKey}
jwt.expiration=86400000